name: CI
on:
  pull_request:
    branches:
      # run test when merging to these branches
      - develop

jobs:
  flutter_test:
    name: Run flutter tests and analyze code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1 # allows to run flutter commands
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test