# Name of your workflow.
name: flutter drive

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
