name: test
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: 
           flutter test
    - name: Install and set Flutter version

    - name: Restore packages
      run: flutter pub get
    - name: Analyze
      run: flutter analyze

    - name: Run tests
      run: flutter test --coverage
