# Name of your workflow.
name: tests-setup

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
 flutter-test:
  name: Run Flutter app tests
  runs-on: ubuntu-latest
  steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.0.0+1'
      - name: Install dependencies 
        run: flutter pub get
      - name: Test app 
        run: flutter test --coverage
        
