# Name of your workflow.
name: tests-setup

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
 test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: 
          - 3.3.0
          - 3.0.0
          - 2.10.5

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        run: flutter test integration_test
        
