# Name of your workflow.
name: tests-setup

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        run: flutter test integration_test
        
