name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Dart SDK
      uses: dartsidedevs/setup-dart-sdk@v1
      with:
        dart-version: stable
    - run: dart pub get
    - run: dart analyze
    - run: dart test
