# Name of your workflow.
name: tests-setup

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
 flutter-test:
  name: Run Flutter app tests
  runs-on: ubuntu-latest
  steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.1'
      - name: Restore packages
        run: flutter pub get
      - run: flutter analyze
      - run: flutter test

        
